<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>G1-S3-DeleteAccountSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>50b2f68f-e465-41fa-87b7-fae21969c42b</testSuiteGuid>
   <testCaseLink>
      <guid>6508b5a6-ab82-425b-98f9-13c35c12d429</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G1-AdminUserManagement/G1-S3-DeleteAccount/G1-S3-TC1-Successfully delete account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cf3b872-9fa3-4f11-acf4-6005762485ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d73a54e-7733-4dfd-864e-694772f9ed68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G1-AdminUserManagement/G1-S3-DeleteAccount/G1-S3-TC2-Users delete more than one account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>782c541b-dcba-4339-a29c-bcbe7fb32125</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
