<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>G1-S2-AddNewAccountSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8aa7441d-d3fa-4358-aeb3-edd25e80f283</testSuiteGuid>
   <testCaseLink>
      <guid>f1802086-8a88-4e8f-9159-5b6e930fb5c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G1-AdminUserManagement/G1-S2-AddNewAccount/G1-S2-TC1-Successfully Add New User (with DDT)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7515015d-81a1-45ee-be7d-6e6b21521202</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/addNewUser</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7515015d-81a1-45ee-be7d-6e6b21521202</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userRole</value>
         <variableId>6c8ccf43-9edc-4f5a-9974-b83c95fd112c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7515015d-81a1-45ee-be7d-6e6b21521202</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>status</value>
         <variableId>963266f4-bb91-4178-a07f-716f14196aab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7515015d-81a1-45ee-be7d-6e6b21521202</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>employeeNameSearch</value>
         <variableId>8425ce4d-75db-419e-abaf-e3d89887b53f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7515015d-81a1-45ee-be7d-6e6b21521202</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>employeeName</value>
         <variableId>d7e8e499-112c-4942-abdc-9cc182952fd3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7515015d-81a1-45ee-be7d-6e6b21521202</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>91133d4f-638e-4d7c-b52e-c55c27480c8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7515015d-81a1-45ee-be7d-6e6b21521202</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>1b026357-c4c6-4174-bf0d-1a6b27a5740d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7515015d-81a1-45ee-be7d-6e6b21521202</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>confirmPass</value>
         <variableId>f724c285-cef4-4d2b-8418-7e52ccd08591</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a544e41-00fd-4948-9fdd-79fc695bb638</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G1-AdminUserManagement/G1-S2-AddNewAccount/G1-S2-TC2-Users enter an unregistered employee name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50573847-ca8f-4b44-a5f2-04d7a7846020</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>366b7f74-7538-4454-9a1c-e0470e2c54d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G1-AdminUserManagement/G1-S2-AddNewAccount/G1-S2-TC3-Users enter less than five characters for username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8faf308-8e90-4e84-9e1f-f7a99283dd0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2104a64f-3099-4a58-9543-cce7d0e50dc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G1-AdminUserManagement/G1-S2-AddNewAccount/G1-S2-TC4-Users enter the registered username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d97c0ab-0b11-4398-b2a9-db6c0cf821ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd2f6451-57cd-417b-92b8-1760e38eff8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G1-AdminUserManagement/G1-S2-AddNewAccount/G1-S2-TC5-Users enter less than eight characters for password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>616cd062-092d-4d4c-953a-428adbd91757</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa47bd83-7200-4783-957e-37b131de4ae2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G1-AdminUserManagement/G1-S2-AddNewAccount/G1-S2-TC6-User did not enter alphanumeric number for password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81f5c3ca-032d-4550-b9d3-8bdf9f53a637</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a24d9b86-546c-4073-bf9b-b020148a267d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G1-AdminUserManagement/G1-S2-AddNewAccount/G1-S2-TC7-Password confirmation does not match password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f605b88-2611-4ca9-9c29-fce5e4429f4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b241833-ca7e-44e1-ac03-2b5873d58f84</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ebf00ff3-291a-4fad-8695-7dd0202ffddd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G1-AdminUserManagement/G1-S2-AddNewAccount/G1-S2-TC8-Users leave the form blank</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b95bcd8-3da2-47f9-8940-1c8d84a1e764</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aa1a33c-ca5a-4ece-98ef-0d4b315016c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9715174b-3253-4ad1-92da-7a7c9b6734f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b1df47f-4a4a-4605-a314-876293207021</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
