<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>G3-S3-DeleteCurrencySuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>77cd360a-94e6-4004-8e0e-be1bf928f9cf</testSuiteGuid>
   <testCaseLink>
      <guid>ef037dca-5e19-4577-99f7-5fa401a783a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G3-AdminJobPayGrades/G3-S3-DeleteCurrency/G3-S3-TC1-Successfully delete a currency</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5a5b19f-b971-4631-80cd-b306d453f525</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e817ef8-005f-4a79-87bb-259b96e7d206</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4fe8f764-52e4-4d2a-af7b-a836da871d40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G3-AdminJobPayGrades/G3-S3-DeleteCurrency/G3-S3-TC2-Users delete more than one currency</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbc2068a-ed72-4d00-bdfc-2d3925a618b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>354b85eb-8ddd-4322-9faf-67b903ae05c6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
