<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>G3-S4-EditCurrencySuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5fecb3dc-211f-44c1-881f-342e5517649e</testSuiteGuid>
   <testCaseLink>
      <guid>5ba8190a-4bd7-4787-9440-79383d957be3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G3-AdminJobPayGrades/G3-S4-EditCurrency/G3-S4-TC1-Successfully edit the amount of minimum salary</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1110e7ce-5f24-4588-b2df-457f86116d51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2de62cae-9f92-4041-a60d-0327812793ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7da23cd5-a7e4-4755-b517-d2d6bfc27f29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07bc9ccd-6a1d-474a-9ad9-14117cfe1f44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G3-AdminJobPayGrades/G3-S4-EditCurrency/G3-S4-TC2-Successfully edit the amount of maximum salary</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65a69bfe-35e6-4140-be5a-4474004b5493</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e598842-d1ea-4497-b169-0a5104152d1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbf4b389-2097-4d25-90f9-c599a7b5d05f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9810e0be-d21b-4ac9-bfd9-a6072f1c0e4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G3-AdminJobPayGrades/G3-S4-EditCurrency/G3-S4-TC3-Users replace the existing saved currency</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f404c0b9-7413-482f-9eee-0157c7441189</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40ffcefc-4e83-4900-a394-700c62c49c87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6011df0a-6776-426b-9fd2-cf860c79110b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2fe4bc8-3c71-4aef-a8da-7451c6a6e02f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G3-AdminJobPayGrades/G3-S4-EditCurrency/G3-S4-TC4-Users enter minimum salary higher than maximum salary</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>409badce-ebdf-4e33-8603-06c3d2be5045</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd2decb3-78ca-48fb-9529-33e38182d01d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f54789f-9097-4381-a9e7-695bfbfa2ccc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
