<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>G3-S2-AddCurrencySuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7f132e2e-02b6-4c0c-87e3-68342da970b6</testSuiteGuid>
   <testCaseLink>
      <guid>a33f07c9-4036-433f-a131-89ac3653b510</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G3-AdminJobPayGrades/G3-S2-AddCurrency/G3-S2-TC1-Successfully add new currency (with DDT)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bfceea39-74c5-4297-8341-a07ad73dd34b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/addNewCurrency</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50b431ee-44d7-4de7-9d40-67d2151df234</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bfceea39-74c5-4297-8341-a07ad73dd34b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>currency</value>
         <variableId>e2193e87-c118-4b85-bc94-f5d9d0c9ecbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bfceea39-74c5-4297-8341-a07ad73dd34b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>minSalary</value>
         <variableId>752b3e06-a941-4295-b245-9a1fc2312e8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bfceea39-74c5-4297-8341-a07ad73dd34b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>maxSalary</value>
         <variableId>ff56fe7b-6422-409b-8ce7-05e34ab4cc15</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4fbd0a83-64bd-4415-be02-84101373b599</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G3-AdminJobPayGrades/G3-S2-AddCurrency/G3-S2-TC2-Users enter invalid currency</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be7fc7cd-2c8d-40ba-8cd4-3859d54ab60f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19f5ef4e-f48f-4b87-abff-1d4362e48746</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad841517-2299-4fb7-81cf-83fd16bf5306</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G3-AdminJobPayGrades/G3-S2-AddCurrency/G3-S2-TC3-Users enter registered currency</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9767135-618c-488e-8b99-0caa710822b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7b83285-9600-4c8a-9b20-ae4935ab87c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>435df471-7c08-4f5c-9ae1-0d2da2e47eac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G3-AdminJobPayGrades/G3-S2-AddCurrency/G3-S2-TC4-Users enter minimum salary higher than maximum salary</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32554c44-d664-4403-af06-3da26b91dd3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>975161e7-a4dc-435e-908a-6d21ec613367</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95c06b59-9488-4211-b054-82bb8496bf8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec550f67-71c6-4536-9d47-ce769f635953</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
