<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>G3-S1-AddPayGradeSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f3e20bfa-0e7b-4cd0-904e-926bdbc28428</testSuiteGuid>
   <testCaseLink>
      <guid>ee2a01ac-dec2-462a-804b-a3a2c8c853a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G3-AdminJobPayGrades/G3-S1-AddPayGrade/G3-S1-TC1-Successfully add new pay grade</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f749f63-0eb2-4657-a19b-772da620bbf7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b73015b4-bd90-4ab9-93e3-114330b36ce3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G3-AdminJobPayGrades/G3-S1-AddPayGrade/G3-S1-TC2-Users enter registered pay grade</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dedfb7d0-ef2f-490b-a389-2fbf3fcea2dd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
