<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>G6-S3-EditSkillSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2d0a77e3-fa30-48ea-99cc-79375a490ca6</testSuiteGuid>
   <testCaseLink>
      <guid>6cb305ac-e818-4d06-ae17-3e5a6449c697</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G6-AdminQualificationsSkills/G6-S3-EditSkill/G6-S3-TC1-Successfully rename the skill</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5521ee22-0988-40de-a79e-aa3ffc54b16e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f997efa-630f-478b-8384-56a5969090d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94e2b996-4335-4935-8ce1-832694577961</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G6-AdminQualificationsSkills/G6-S3-EditSkill/G6-S3-TC2-Users enter the same skill name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a418acf-c558-4402-988e-26314a6d84dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10e76716-e485-428b-a6b4-7c57201e8852</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7a606ae7-0ddb-4cfa-a721-119aaa8ed293</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G6-AdminQualificationsSkills/G6-S3-EditSkill/G6-S3-TC3-User did not enter skill name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3281f0f-eddf-4ca2-8b2b-715e4aa33c9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dfbe75e-ee8e-4367-86c9-d3bdf0b399ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a2c55e7-4b8c-4c6c-8707-d129cd5beeec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G6-AdminQualificationsSkills/G6-S3-EditSkill/G6-S3-TC4-Users leave the form blank</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d07f9be8-5f97-4901-b56d-af4cca85fc2a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
