<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>G2-S2-DeleteJobTitlesSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0a111505-cd71-495e-be32-ae590b583409</testSuiteGuid>
   <testCaseLink>
      <guid>842e74e9-97c5-4824-983f-720949d84557</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G2-AdminJobTitles/G2-S2-DeleteJobTitles/G2-S2-TC1-Successfully delete a job title</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ff123c9-4b6c-4497-b687-43837af703b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb2552c3-449a-4ab8-baae-990a1b950efd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G2-AdminJobTitles/G2-S2-DeleteJobTitles/G2-S2-TC2-Users delete more than one job titles</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb09f518-fbdb-4e4f-81eb-2b9ca4efe510</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
