<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>G2-S1-AddJobTitlesSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3b379156-bafa-4dc8-89ef-fe0a94639bdd</testSuiteGuid>
   <testCaseLink>
      <guid>fa3b93b8-d53d-46d3-a57f-2d69e6939f5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G2-AdminJobTitles/G2-S1-AddJobTitles/G2-S1-TC1-Successfully add new job title</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0365cb8b-4c0c-4b69-8b6f-7d737203b44c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0359153-3e05-4197-a772-dd9162d3160f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6d70637-3b1d-4828-8bcb-72183ecef3e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db4f3a8a-2950-4b17-b238-510a7010ea4b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97bdd19f-4903-4e97-b855-6ba1591cc414</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G2-AdminJobTitles/G2-S1-AddJobTitles/G2-S1-TC2-Users enter registered job title</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9121dbd-1575-4959-8a4b-14a48d44a305</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f738965f-dd24-466b-998c-02fe5105453e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G2-AdminJobTitles/G2-S1-AddJobTitles/G2-S1-TC3-Users select file more than 1 MB</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a59b99be-5ccb-46dd-a3d3-3efa64f52e02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00b881a6-4b6d-4787-9fcd-de61c69a7fbb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89867676-646a-463c-b889-de60b4311549</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G2-AdminJobTitles/G2-S1-AddJobTitles/G2-S1-TC4-User leave job title blank</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
